FROM node:19-alpine3.16
ARG username=NRuser
ARG reldir=/home/${username}
ARG workdir=${reldir}/personal-site/client

# Requires root user perms.
RUN apk update && \
    apk add openssh && \
    apk add git && \
    apk add sudo

# Configure sudo for initialization tasks. 
RUN echo "NRuser ALL=(ALL) NOPASSWD: /home/NRuser/personal-site/scripts/init.sh" >> /etc/sudoers && \
    echo "NRuser ALL=(ALL) NOPASSWD: /bin/chown" >> etc/sudoers

# Create and switch to non-Root User.
RUN mkdir ${reldir}
RUN adduser --disabled-password -h ${reldir} ${username} 
WORKDIR ${workdir}


# Update Package Management and Install Dependences
COPY package*.json . 
RUN  npm install

# Copy source files
COPY . .

EXPOSE 3000

USER ${username}